### ISSUE TITLE
Cannot get proper value to show when evaluating hands

### ISSUE THREAD

**Issue by niddy1** [niddy1/Blackjack#2]
## UserStory
- As a user I want to play a hand of blackjack against a computer opponent so that I can become a better player.

Test Statement

When I evaluate a hand, the loop stops after 1 element. I believe  new hand being dealt is messing things up
## Context & Description

When Im running a loop to sum up the values it only returns one of the two values.
I have tried console log on line 205, it shows that my array has a length of 0
I believe that a new hand being created outside the function is messing things up
No Error Message

```
Dealer.prototype.evalulateHand = function(){
    //console.log(this.dealerHand[0].value);
    console.log(this.dealerHand);
    var playerValue = 0;
    var dealerValue = 0;
    console.log(dealerHand.length);
    for (var i = 0; i <= dealerHand.length; i++){

        console.log("");
        console.log(this.dealerHand[i]);

        //console.log(this.dealerHand[i].value)
        //dealerValue = dealerValue + this.dealerHand[i].value
    }
    console.log( dealerValue = dealerValue + this.dealerHand[i].value);
    //console.log(dealerValue)
};

dealerIan.evalulateHand();
```

Above is where I'm running into the problem, but I believe the problem is created earlier.

**Comment by iiVi** [comment]
Helped in person.
