### ISSUE TITLE
Cannot bind card values to images

### ISSUE THREAD

**Issue by niddy1** [niddy1/Blackjack#3]
## UserStory
- As a user I want the interface to be attractive so I don't have to stare at text.
## Test Statement

when I hit new game, 4 image cards should show up on my display
## Context & Description
- When I evaluate try to look inside my card object it returns undefined, from there I am having a hard time figuring out how to link it with images. Also having a problem understanding what is happening with document.ready
## Error Message
- Uncaught TypeError: Cannot read property '0' of undefined

```

var test = this.dealerHand[0].symbol +"_of_"+ this.dealerHand[0].suit+".png"
Dealer.prototype.bindCards = function(){
  //for (){
    dealerCard1=this.dealerHand[0].symbol +"_of_"+ this.dealerHand[0].suit
    3_of_spades
    $(".dealer-cards").append($("<img>").addClass("playing-cards").attr('src',test))
    $(".dealer-cards").append($("<img>").addClass("playing-cards").attr('src',"cards/3_of_clubs.png"))
  //}
}
```

**Comment by amadden80** [comment]
```
var test = this.dealerHand[0].symbol +"_of_"+ this.dealerHand[0].suit+".png"
```

This code here looks like it is NOT inside the object.  Therefore the `this` here refers to something completely different.  Is that where the issue is?  If you remove that test line, do you still get the same error?

**Comment by niddy1** [comment]
Yeah it wasn't inside the object. I realize now that I have to call it as dealerIan.dealerHand. I'm still in the process of getting images to work properly but I'm not stuck on this current issue.
Thanks
